<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- Si la versión del SDK empieza por "10.", usa .NET 10.0 -->
  <PropertyGroup Condition="$(NETCoreSdkVersion.StartsWith('10.'))">
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <!-- Para cualquier otra versión (como 9.x, 8.x) o si no está definida, usa .NET 9.0 -->
  <PropertyGroup Condition="!$(NETCoreSdkVersion.StartsWith('10.'))">
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

</Project>